#!/bin/sh

#define	KERN_EMERG		"<0>"	/* system is unusable			*/
#define	KERN_ALERT		"<1>"	/* action must be taken immediately	*/
#define	KERN_CRIT		"<2>"	/* critical conditions			*/
#define	KERN_ERR		"<3>"	/* error conditions			*/
#define	KERN_WARNING	"<4>"	/* warning conditions			*/
#define	KERN_NOTICE		"<5>"	/* normal but significant condition	*/
#define	KERN_INFO		"<6>"	/* informational			*/
#define	KERN_DEBUG		"<7>"	/* debug-level messages			


if [ $# -ne 1 ]; then
	echo ""
	echo "Usage:"
	echo "/ # printk 3"
	echo ""
	echo "Current printk level"
	cat /proc/sys/kernel/printk
	exit 1
fi

if [ $1 == "0" ]; then
	echo "NO KERNEL MESSAGE"
	echo "0 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "1" ]; then
	echo "KERN_EMERG"
	echo "1 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "2" ]; then
	echo "KERN_EMERG/ALERT"
	echo "2 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "3" ]; then
	echo "KERN_EMERG/ALERT/CRIT"
	echo "3 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "4" ]; then
	echo "KERN_EMERG/ALERT/CRIT/ERR"
	echo "4 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "5" ]; then
	echo "KERN_EMERG/ALERT/CRIT/ERR/WARNING"
	echo "5 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "6" ]; then
	echo "KERN_EMERG/ALERT/CRIT/ERR/WARNING/NOTICE"
	echo "6 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "7" ]; then
	echo "KERN_EMERG/ALERT/CRIT/ERR/WARNING/NOTICE/INFO"
	echo "7 1 4 7" > /proc/sys/kernel/printk
elif [ $1 == "8" ]; then
	echo "KERN_EMERG/ALERT/CRIT/ERR/WARNING/NOTICE/INFO/DEBUG"
	echo "8 1 4 7" > /proc/sys/kernel/printk
else
	echo ""
	echo "Usage:"
	echo "/ # printk 3"
	echo ""
	exit 1
fi

cat /proc/sys/kernel/printk

